### ISSUE TITLE
Question: Is it possible to change default growth rate of specific crystals?

### ISSUE THREAD

**Issue by AbsorbingSafe11** [XFactHD/BuddingCrystals#1]
I would like to know if it is possible (even on my end though the use of configs or JSON edits) to make specific crystals grow faster or slower, mainly because salt crystals would need to grow really fast in order to be a viable means of generating salt, as well as, a few others growing a bit too fast. (diamonds and emeralds)
As, a possible solution, Would it be possible for tiers of crystal to be made? (0 to 5 tiers, amethyst tier of 3, salt tier 0, diamonds tier 5 and growth rate is determined by tier, where higher tier is slower growth and lower tier is faster growth)

**Comment by AbsorbingSafe11** [comment]
I don't know how to add tags to the issue, so hopefully the title is good enough to show this is a question.

**Comment by XFactHD** [comment]
If you are using the currently latest version (1.1.0), then you can override the builtin crystals via JSON. See [the wiki](https://github.com/XFactHD/BuddingCrystals/wiki/Custom-Crystals) and the paragraph "Overriding builtin crystals" for how to do this and what the different values in the JSON mean.

You can find the default values, which you will need to provide for anything you don't want to change, [here](https://github.com/XFactHD/BuddingCrystals/blob/1.18.x/src/main/java/xfacthd/buddingcrystals/common/BCContent.java#L27-L86) in the creation of the builtin crystals. The default values for drops are 2 for normal and 4 for max drops and the default growth chance value is 5.
I'll think about adding a command to export configurations of the builtin crystals in the next version to make this a lot easier.

Please keep in mind that the growth of the crystals is connected to random ticks, so the maximum growth speed is limited by the random tick speed you have set.
If you find some good values, feel free to mention them and I may include them as the default values in an upcoming version.

**Comment by AbsorbingSafe11** [comment]
The only growth speed I can really say is Salt needs a growth chance of 1, as if it doesn't grow super fast , the desalination system (for getting salt from water) in Mekanism will render the salt crystals nearly useless. (they will still be useful for decoration)

Also, the general rule of thumb I use for growth rates (or will use now that I know how to adjust them) is that time required to obtain them in other ways needs to be comparable to the growth rate of the crystals. (like diamonds could take an hour or two, in order to find, but glowstone takes a few minutes in the nether) 

Additionally, thanks for explaining how to adjust growth rates myself. (and I can use randomtickspeed commands to test slower growth rates)

**Comment by XFactHD** [comment]
The export command is included in the latest version.
I have also set the salt crystals growth chance to 1.
As such I'll close this issue for now.

PS: If you have balancing suggestions, please feel free to mention them and I'll include them in an upcoming update. I am really bad at balancing, which is why the mod is in this completely unbalanced state.
