### ISSUE TITLE
[Suggestion] Hide items.

### ISSUE THREAD

**Issue by Kevin-Marsh** [XFactHD/BuddingCrystals#10]
I just wanted to suggest hiding the items if they are disabled in the config. This would make it a bit cleaner and avoid confusion.

**Comment by XFactHD** [comment]
This is unfortunately not possible. The type of config that currently controls the recipes is not synchronized with the client, which means that if a server disables a recipe, you would still see the respective block in the creative inventory and every recipe viewer that uses the creative inventory as its data source, and if you disable it on your client but the server doesn't, then you wouldn't see the block in the creative inventory despite it being craftable, which is in my opinion even more confusing than an uncraftable but visible block. The type of config that would be synced to the client is loaded too late to control the recipes, making it unable to fullfil its primary purpose.
