### ISSUE TITLE
Balancing Idea

### ISSUE THREAD

**Issue by Phat-Rat1** [XFactHD/BuddingCrystals#11]
Adding config options to allow players to balance as they see fit might be a good idea.  A few possibilities for options:
Chance to grow on a random tick (0.00 to 1.00)
How many crystals drop when mined (any real positive number)
Options for how many crystals and how many crystal blocks to use in the crafting recipe (0 to 8, but must add up to at least 1 and no more than 8).  For example, for diamond budding crystals, you could set the recipe to use 2 diamond and 2 blocks of diamond

**Comment by XFactHD** [comment]
This mod is already fully configurable by using the crystal definition files. See the [wiki page](https://github.com/XFactHD/BuddingCrystals/wiki/Custom-Crystals) for the file format. The builtin crystal definitions can be exported with the `/buddingcrystals export_all` command and then modified as desired.
