### ISSUE TITLE
[Crash}: Worldgen mods causing a unbound biome registry crash on 1.20.1 forge when buddingcrystals is introduced

### ISSUE THREAD

**Issue by Mysticpasta1** [XFactHD/BuddingCrystals#13]
Full log -> https://gist.github.com/Mysticpasta1/aba3924fc9a2e967205c7885615a6ea3

**Comment by Mysticpasta1** [comment]
all mods work by themselves but when adding budding crystals with any worldgen mod it breaks on world load or creation

**Comment by Mysticpasta1** [comment]
list of Worldgen mods it crashes with
Good Ending
RiverRedux
Galosphere
Geologic Expansion
Wood Enjoyer
these are just a few of them

**Comment by Mysticpasta1** [comment]
https://gist.github.com/Mysticpasta1/aba3924fc9a2e967205c7885615a6ea3 <- Full log

**Comment by XFactHD** [comment]
I've decided to fix this for 1.20.1 with something very similar to the simple solution you initially suggested by using `RegistryAccess.EMPTY`. For 1.21 I will still have to find a different solution.
