### ISSUE TITLE
Mekanism clusters drop nothing when mined without silk touch

### ISSUE THREAD

**Issue by Rocnix** [XFactHD/BuddingCrystals#5]
The loot tables show minecraft:air where most clusters have their respective gems, and in-game they lack a recipe and drops.

**Comment by XFactHD** [comment]
I need a lot more info to help you.

- Which Minecraft version?
- Which Forge version?
- Which BuddingCrystals version?
- Do you have Mekanism installed? If yes, which version?

At this point, the only guess I have is that you don't have Mekanism installed, which would mean that both the recipe and the loot table are intentionally disabled to prevent issues.

**Comment by Rocnix** [comment]
Minecraft 1.19.2, Forge 43.2.3, BuddingCrystals-2.1.0, and Mekanism-1.19.2-10.3.5.473 (plus mekanism generators, but not the whole set of mekanism mods). I also don't have applied energistics, if that matters.

The loot table is at least partially working, because the buds and clusters drop themselves when silk touched.

I haven't updated Mekanism particularly recently, so it might be that budding crystals thinks it isn't there?

I'm using datapacks as a workaround for now, so I'm mostly saying this in case someone else ends up with the same or a similar problem.

**Comment by XFactHD** [comment]
Thank you for the details, I'll have to look into this. It's possible that Mekanism changed the internal name of the item, which I missed. I doubt the issue is in the detection of the presence of Mekanism though.

**Comment by XFactHD** [comment]
Found the issue, I had incorrectly generated the data while the relevant mods were not present, so the items were missing and therefore defaulted to "minecraft:air".
I hope to get a new version out within the coming days.
