### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by Spankster206** [XFactHD/BuddingCrystals#6]
I am posting this because it is easier for you to respond too, and I completely respect ease of access. For outside readers, this is about compatibility between my mod (Amethyst Touch, soon to be Crystal Touch I hope) and Budding Crystals. I would like to ask if you could tag the blocks as simply "Budding Blocks" and then that would make it easier for compatibility. Thank you!

**Comment by XFactHD** [comment]
I'll tag them as `forge:budding_blocks` as that seems like the most sensible variant of your suggestion.
