### ISSUE TITLE
AE2 Annilation Plane Break Timing Issues

### ISSUE THREAD

**Issue by Meepin** [XFactHD/BuddingCrystals#7]
I am currently running a custom modpack which includes AE2 and Budding Crystals. With the AE2 budding Certus quartz, I just need to limit the storage locations to Certus quartz crystals and it will only break on full growth, but with budding crystals, it will break on first growth and not harvest properly. I am not sure if this is on AE2's end, this mod's end or a tagging issue or even a special coding in AE for the breaking timing, but I am notable to automate this mod with AE2 until this is resolved.

Please Reply, even if only tell me this is an issue on AE2's end.

Just to clarify, this is on the 1.20.1 version of both mods

**Comment by Technici4n** [comment]
You need to enable silk touch - if there is no drop AE2 will break the block regardless of the network filter.

**Comment by XFactHD** [comment]
This would also occur with vanilla Amethyst. The difference between Certus and my blocks is that Certus drops dust when the buds are broken while mine don't drop anything (unless you use silk touch). See the comment above for the solution.

**Comment by Meepin** [comment]
Oh, sorry, I just realized this earlier today, I just hadn't closed out this thread yet. 

Thank you so much for the clarification

![image](https://github.com/XFactHD/BuddingCrystals/assets/5864626/bf33fe71-ab6f-423c-b287-04ea94e26104)

**Comment by Meepin** [comment]
sorry to be a bother, but is there a reason they are not growing when it is set up like this?

**Comment by XFactHD** [comment]
That should work fine. I'll have to look into that some time in the coming days.

**Comment by Meepin** [comment]
just to clarify, I have been leaving it AFK, among other things, for nearly 10 hours with no growth or deposits in the output chest
 I can provide a list of all mods in my custom pack to verify compat issues if you need

**Comment by XFactHD** [comment]
Finally got back to this now, I can't reproduce the issue you are seeing though.

- Do the crystals grow if you disable or remove the annihilation planes?
- Are the annihilation planes all enchanted with silk touch?

It's also worth mentioning that you need a slightly more complex setup to farm BuddingCrystals and vanilla amethyst budding blocks. This is documented in the AE2 guide: https://guide.appliedenergistics.org/#/1.20.1/ae2:example-setups/amethyst-farm.md

**Comment by Murpas** [comment]
Hey there, the farm as solution does not work - it mines the Budding Clusters with silk-touch but cannot process them further on.
